spring.application.name=app

# --- Configurações de Conexão com o Banco ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tickevent_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configurações do Hibernate (JPA) ---
# 'update' faz com que o Spring crie e atualize as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal os comandos SQL que o Spring está executando por debaixo dos panos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true