spring.application.name=app

# ----------------------------------------
# CONFIGURAÇÕES DE CONEXÃO COM O POSTGRESQL
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/tickevent_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ----------------------------------------
# O dialeto ensina o Spring a falar o SQL exato do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra o SQL gerado no console (ótimo para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estratégia de geração de tabelas
spring.jpa.hibernate.ddl-auto=update

# ----------------------------------------
# CONFIGURAÇÕES JWT
# ----------------------------------------
jwt.secret=${JWT_SECRET:dGlja2V2ZW50LWJhY2tlbmQtc2VjcmV0LWtleS0yNTYtYml0cy1obWFjLXNoYTI1Ng==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}